name: .conda
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.11.11
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025b
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - asgiref==3.8.1
      - beautifulsoup4==4.13.4
      - blinker==1.9.0
      - certifi==2025.4.26
      - channels==4.2.2
      - charset-normalizer==3.4.2
      - click==8.2.0
      - dash==2.18.2
      - dash-bootstrap-components==1.7.1
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - django==5.2.1
      - django-bootstrap4==25.1
      - django-plotly-dash==2.4.6
      - dpd-components==0.1.0
      - dpd-static-support==0.0.5
      - flask==3.0.3
      - idna==3.10
      - importlib-metadata==8.7.0
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - markupsafe==3.0.2
      - narwhals==1.38.2
      - nest-asyncio==1.6.0
      - numpy==2.2.5
      - packaging==25.0
      - plotly==6.0.1
      - requests==2.32.3
      - retrying==1.3.4
      - six==1.17.0
      - soupsieve==2.7
      - sqlparse==0.5.3
      - typing-extensions==4.13.2
      - urllib3==2.4.0
      - werkzeug==3.0.6
      - zipp==3.21.0
